# Generated by Django 3.0.5 on 2020-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTBLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='images/')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
