# Generated by Django 3.0.5 on 2020-05-16 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloogapp', '0002_postblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 18, 53, 29, 632898)),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
