# Generated by Django 3.0.5 on 2020-05-16 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloogapp', '0003_auto_20200516_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 18, 54, 19, 931789)),
        ),
    ]
