# Generated by Django 3.0.5 on 2020-05-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloogapp', '0004_auto_20200516_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
